### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kian-mc** [CadenKoehl/CadenBot#6]
A command called -orderinthecourt or -order where it server mutes everyone but the person who issued the command (moderators only)
Also, it only mutes for x amount of time so you could do <-order 20> and it would mute everyone for 20 secs.

If you accidentally do <-order 200> or you want it to end then do -orderstop

I understand if this might be too difficult but it would be useful for some servers.

**Comment by CadenKoehl** [comment]
This is a good idea, however, this is not a priority, and I don't really have time to make this. If you would like to make a pull request and write it yourself then absolutely!
