### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by kian-mc** [CadenKoehl/CadenBot#7]
A -pause command for cadenbot's music feature would be a nice addition so that if you want to pause it for a sec It don't clear your queue.   Or have -stop not clear your queue and instead have leaving the call clear the queue

**Comment by CadenKoehl** [comment]
I just added that! The bot is now live with the changes and I will be uploading the code for it shortly! Instead of a stop command, it's -clear, and there is a new command called "pause".
