### ISSUE TITLE
[feature suggestion]       A -purge command

### ISSUE THREAD

**Issue by kian-mc** [CadenKoehl/CadenBot#9]
A `-purge` command would be a great addition to CadenBot to help with moderation.  the command could be `-purge (x amount of messages to be deleted)` or something else ig. It would also be help full that you could have a second command that warns each person who contributed to the messages that were purged, like `-ultrapurge (x amount of messages)`  and it would say in an embed `purged (number of messages deleted) and ( number of people who were warned) was warned.` Thanks! also no rush I know ur busy

**Comment by CadenKoehl** [comment]
Great idea! I will get to work on this!
